# Generated by Django 4.0.4 on 2022-06-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVTEstudioGrabacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cantantes',
            new_name='Cantante',
        ),
        migrations.RenameModel(
            old_name='Discos',
            new_name='Disco',
        ),
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Musicos',
            new_name='Musico',
        ),
    ]
